### ISSUE TITLE
Info/Warning Messages - Indent information message

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#11]
Body copy of information message needs to be indented so that it is inline with title.
<img width="410" alt="Screenshot 2019-11-18 at 11 22 06" src="https://user-images.githubusercontent.com/10854265/69048566-b49c4880-09f5-11ea-88bb-c8488d8c6b95.png">

**Comment by daylesalmon** [comment]
Fixed in commit: d6652adf79100c8785be1289258d30e998630232
