### ISSUE TITLE
OneApp-Carhire-Carclub-Icons

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#125]
**Is your feature request related to a problem? Please describe.**
We are building a new app which incorporates new mods of transport, we therefore need new modal icons created to support this.

**Describe the solution you'd like**
We need 2 new icons, 1 for CarClub and 1 for CarHire

**Describe alternatives you've considered**

**Additional context**

**Comment by mrmjprice** [comment]
Hi Sam

Sorry about the time delay on this. We'll jump on them tomorrow.

**Comment by mrmjprice** [comment]
Hi @samanthabinns 

@KaterinaKir and I are proposing that Car Hire is: https://fontawesome.com/icons/garage-car?style=solid as you need to go to a physical place to hire the car

Proposals:
- Car Hire: either [garage](https://fontawesome.com/icons/car-garage?style=solid) / [second option garage](https://fontawesome.com/icons/garage-car?style=solid) or a car with a key
- Car Club: either [a car with a pin overhead](https://i.imgur.com/7KFtWgE.png) or [a car with a chevron pointing down](https://i.imgur.com/xm4uQG8.png)

Can you confirm which proposals are preferred and we'll draw them and put them into the design system.

(The car style will be matched)

Martin

**Comment by samanthabinns** [comment]
Hi Martin,

How are you?

So sorry for the delay in coming back to you, this got lost in my inbox!

Thank you for your proposals. I think the following options are good. Can I ask you to consider how they will look on the map and also whether they fit into the filter panel buttons. My concern is that it will be tight to fit these icons combined with the name. As ‘car hire’  and ‘car club’ is quite long. Would be good to get your guidance on this, are you able to provide an example of what you see it looking like in situ?

  *   Car Hire: second option garage<https://fontawesome.com/icons/garage-car?style=solid>
  *   Car Club: a car with a pin overhead<https://i.imgur.com/7KFtWgE.png>

Kind regards,
Samantha Binns
Swift Customer Experience Expert


Direct Dial: 0121 214 7662
Email: Samantha.Binns@tfwm.org.uk
Website: www.tfwm.org.uk

[cid:image001.jpg@01D5FD13.38FF0260]

[Transport for West Midlands]<https://www.tfwm.org.uk/>[cid:image003.jpg@01D5FD13.38FF0260]<https://www.transporttimes.co.uk/news.php/19th-Annual-National-Transport-Awards-Reward-Innovative-Transport-Projects-across-the-Nation-469/>

National Transport Awards, City-Region Transport Authority of the Year:  2016, 2017 & 2019

Building a healthier, happier, better connected and more prosperous West Midlands
Transport for West Midlands, 16 Summer Lane, Birmingham, B19 3SD

Confidentiality: The information in this email may be confidential, contain personal and/or sensitive information, and/or may be legally privileged.  If an addressing or transmission error has misdirected this email, please notify the author by replying to this email and then deleting the original and your reply.  If you have received this email in error, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on the email, may be prohibited and potentially unlawful.  Any views or opinions expressed in this email are those of the sender and do not necessarily reflect the views of West Midlands Combined Authority, unless explicitly stated otherwise.

Find out about WMCA by visiting https://www.wmca.org.uk

[cid:image004.jpg@01D5FD13.38FF0260]Please consider the environment before printing this email.

**Comment by mrmjprice** [comment]
Hi Sam

I'll look at these this afternoon. 😄

**Comment by mrmjprice** [comment]
Managed to get them done now

![](https://i.imgur.com/DCmyoUM.png)

**Comment by mrmjprice** [comment]
![](https://i.imgur.com/VNHPhaf.png)

![](https://i.imgur.com/ynNWHQz.png)

**Comment by samanthabinns** [comment]
Thank you.

Based on one of your previous recommendations we agreed to remove the words from the icons displayed on the map. So on the map, only the icon should be displayed.

Can you also advise what modal colours we should use for those icons? As Unicard will be reviewing my below proposal before public launch in June, this is to create more visual differentiation as in a zoomed out state all we see is purple clusters.

[cid:image001.png@01D5FE96.39BF3740]


Samantha Binns
Swift Customer Experience Expert


Direct Dial: 0121 214 7662
Email: Samantha.Binns@tfwm.org.uk
Website: www.tfwm.org.uk

[cid:image002.jpg@01D5FE96.39BF3740]

[Transport for West Midlands]<https://www.tfwm.org.uk/>[cid:image004.jpg@01D5FE96.39BF3740]<https://www.transporttimes.co.uk/news.php/19th-Annual-National-Transport-Awards-Reward-Innovative-Transport-Projects-across-the-Nation-469/>

National Transport Awards, City-Region Transport Authority of the Year:  2016, 2017 & 2019

Building a healthier, happier, better connected and more prosperous West Midlands
Transport for West Midlands, 16 Summer Lane, Birmingham, B19 3SD

Confidentiality: The information in this email may be confidential, contain personal and/or sensitive information, and/or may be legally privileged.  If an addressing or transmission error has misdirected this email, please notify the author by replying to this email and then deleting the original and your reply.  If you have received this email in error, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on the email, may be prohibited and potentially unlawful.  Any views or opinions expressed in this email are those of the sender and do not necessarily reflect the views of West Midlands Combined Authority, unless explicitly stated otherwise.

Find out about WMCA by visiting https://www.wmca.org.uk

[cid:image005.jpg@01D5FE96.39BF3740]Please consider the environment before printing this email.

**Comment by samanthabinns** [comment]
I think we should go with the below. The thickness of the lines look more aligned to the other mode icons.

[cid:image006.png@01D5FE98.45E99E00]


Samantha Binns
Swift Customer Experience Expert


Direct Dial: 0121 214 7662
Email: Samantha.Binns@tfwm.org.uk
Website: www.tfwm.org.uk

[cid:image007.jpg@01D5FE98.45E99E00]

[Transport for West Midlands]<https://www.tfwm.org.uk/>[cid:image009.jpg@01D5FE98.45E99E00]<https://www.transporttimes.co.uk/news.php/19th-Annual-National-Transport-Awards-Reward-Innovative-Transport-Projects-across-the-Nation-469/>

National Transport Awards, City-Region Transport Authority of the Year:  2016, 2017 & 2019

Building a healthier, happier, better connected and more prosperous West Midlands
Transport for West Midlands, 16 Summer Lane, Birmingham, B19 3SD

Confidentiality: The information in this email may be confidential, contain personal and/or sensitive information, and/or may be legally privileged.  If an addressing or transmission error has misdirected this email, please notify the author by replying to this email and then deleting the original and your reply.  If you have received this email in error, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on the email, may be prohibited and potentially unlawful.  Any views or opinions expressed in this email are those of the sender and do not necessarily reflect the views of West Midlands Combined Authority, unless explicitly stated otherwise.

Find out about WMCA by visiting https://www.wmca.org.uk

[cid:image010.jpg@01D5FE98.45E99E00]Please consider the environment before printing this email.

**Comment by mrmjprice** [comment]
Hi Sam

We can't see what you're referring to as you're replying via email, it's scrambling links and images.

Please can you reply via [Github](https://https://github.com/wmcadigital/wmn-design-system/issues/125)?

**Comment by samanthabinns** [comment]
Hi guys sorry.

Based on one of your previous recommendations we agreed to remove the words from the icons displayed on the map. So on the map, only the icon should be displayed.

Can you also advise what modal colours we should use for those icons? As Unicard will be reviewing my below proposal before public launch in June, this is to create more visual differentiation as in a zoomed out state all we see is purple clusters. Refer to slide 5 in the attachement.

See slide 6 for my preferred icon recommendations.

Let me know if you have questions.

[OneApp_XD_Amends_V1.pptx](https://github.com/wmcadigital/wmn-design-system/files/4358728/OneApp_XD_Amends_V1.pptx)

**Comment by samanthabinns** [comment]
Hi guys, any update on this please?

**Comment by mrmjprice** [comment]
[OneApp - Third party car icons (SVG and PNG).zip](https://github.com/wmcadigital/wmn-design-system/files/4486388/OneApp.-.Third.party.car.icons.SVG.and.PNG.zip)

Hi Sam, here are the icons. Not sure if you still need these shown on a map?

**Comment by samanthabinns** [comment]
Thanks Martin. Yes please can you mock that up?

**Comment by mrmjprice** [comment]
![Car Hire and Club icons](https://user-images.githubusercontent.com/10854265/79841553-81e4ea80-83af-11ea-813b-b5540ed4fdb5.png)
