### ISSUE TITLE
Content Tiles - Background Colour

### ISSUE THREAD

**Issue by rolorogan** [wmcadigital/wmn-design-system#135]
When adding content tiles to a background that is not white makes the tile transparent as there's no white background on the tile.

There does not seem to be a colour palette for a white background.

![Screenshot 2020-03-13 at 11 36 23](https://user-images.githubusercontent.com/7985514/76617847-0de93400-651f-11ea-8e51-972cb71bdf55.png)

**Comment by daylesalmon** [comment]
This is about to be closed with my latest push.
