### ISSUE TITLE
Refresh Icon for OneApp

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#215]
Hi guys,

Can you source a refresh icon for OneApp. Would recommend using one similar to NWM app as existing users will be familiar with it.

Can you get something over by the end of the week please?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrmjprice** [comment]
Hi @samanthabinns - We have done this and is queued for Dayle to approve.

The **sync** icon can be seen on this preview page: https://deploy-preview-216--wmnetwork.netlify.app/styles/icons/

**Comment by samanthabinns** [comment]
Wicked, thank you!
