### ISSUE TITLE
Buttons with icons in IE11

### ISSUE THREAD

**Issue by rolorogan** [wmcadigital/wmn-design-system#217]
Buttons with icons don't work in ie11
![Screenshot 2020-05-26 at 16 51 21](https://user-images.githubusercontent.com/7985514/82922614-ba10b780-9f71-11ea-87f4-f2c8034d4a69.png)

**Comment by daylesalmon** [comment]
I've managed to get this working on the disruptions app: https://disruptions.wmnetwork.co.uk/
@daylesalmon to implement the solution in the design system and update the icons page with new copy on how to better implement icons.
