### ISSUE TITLE
Header and footer page accessibility issues

### ISSUE THREAD

**Issue by gldgrnt** [wmcadigital/wmn-design-system#283]
**Describe the bug**
Component examples on the Header and footer page are the same as the ones being used globally on the site and are therefore causing AXE to flag the following issues:

- **Heading levels should only increase by one** - caused by `h1` used in the 'With title variant in header' example
- **Ensure landmarks are unique** - caused by header navigation example matching the site's navigation

[https://designsystem.wmnetwork.co.uk/patterns/header-and-footer/](https://designsystem.wmnetwork.co.uk/patterns/header-and-footer/)

**Comment by daylesalmon** [comment]
Relates to #287
