### ISSUE TITLE
Iframe (map) accessibility issues 

### ISSUE THREAD

**Issue by houbly** [wmcadigital/wmn-design-system#284]
There are a number of colour contrast issues with the Iframe (map) content tile. Dots navigation colours and content within the legend dropdown don't meet contrast requirements

![image](https://user-images.githubusercontent.com/6360479/90387729-99429480-e07e-11ea-8f8f-5f65d983f3c2.png)

**Comment by KaterinaKir** [comment]
Hi Houston, we are not updating this since it is old content and it will be reviewed by content editors when they start updating content and migrating to new site.
Thanks
