### ISSUE TITLE
Beta button

### ISSUE THREAD

**Issue by catiarodriguescosta** [wmcadigital/wmn-design-system#291]
**Describe the bug**
As it is a button, it is accessible via keyboard. His function is to led people to homepage again. 
The button appears twice: in the navbar, close to the logo, and bellow the navbar section, on the "alert" section.

Should this beta button have that importance? Is it clear that it goes to the homepage?

<img width="839" alt="Screenshot 2020-08-17 at 15 09 12" src="https://user-images.githubusercontent.com/34938764/90405426-a0c46680-e09b-11ea-9dfc-0c719b014d62.png">

**Comment by daylesalmon** [comment]
Relates to #287

**Comment by KaterinaKir** [comment]
Hi Catia, 
Please remove beta banner from top header, next to logo. You are right, we don't need two beta banners on one page. Thanks
