### ISSUE TITLE
The phase banner text appears below the phase icon on small devices

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#298]
<img width="324" alt="Screenshot 2020-08-18 at 12 08 16" src="https://user-images.githubusercontent.com/10854265/90506009-80ec7b80-e14b-11ea-9f12-338da37ef843.png">

* Can the text begin on the same line as [ BETA ] ?
* Tested using iPhone SE size (320 width).

**Comment by daylesalmon** [comment]
I would hold off on this change for now until we get a solution from #291. Otherwise you could fix it and then have to remove the button from the banner anyway. So keep an eye on #291's solution before tackling this.
