### ISSUE TITLE
UI5.1 - Design system documentation

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-design-system#3]
**Epic:** Externally-accessible design system

***
#### As a
designer and developer (internal and external)

#### I need
to know how to use patterns and components

#### In order to
create a coherent user interface and experience

***

✏️ **Design Size:** ♾
⌨️ **Dev Size:** ♾

***

#### Acceptance criteria
Can I...?
- [x] Documentation for each component/pattern live on the design system
  - [x] What it is
  - [x] How to use it
  - [x] When to use it
  - [x] When not to use it
  - [x] Research and further reading

***

**Comment by daylesalmon** [comment]
A great resource for [documenting and presenting components in a design system].(https://medium.com/eightshapes-llc/documenting-components-9fe59b80c015 )

Would we benefit by breaking this issue up in to more specific issues, such as 'checkbox component requires documentation' or 'primary button component needs accessibility documentation'?

**Comment by mrmjprice** [comment]
We'll refine it once we've got to it 😄

**Comment by daylesalmon** [comment]
As this is an ongoing thing and it is somewhat up to date as of today, I'm going to close this issue.
