### ISSUE TITLE
Styling external links and content blocks

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#321]
## What
> We currently only have one style of link, which does not inform the user they are leaving our website.

## Why
>Explain why you think this should be added to the West Midlands Network Design System (WMN DS).
>
>- A lot of content is being rewritten and pointing to other websites if they can provide better content than us
>- We need to tell users they are leaving the site so they can expect to end up on a new website
>- We have a link style, but should extend it

## Anything else
> GOV.UK [removed the external link from the Design System](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/) because they found users did not understand what it meant
> 
> TfL have icons next to external links
> <img width="351" alt="Screenshot 2020-08-20 at 08 33 18" src="https://user-images.githubusercontent.com/10854265/90730323-d34ea900-e2bf-11ea-8ddc-f349015bfbe4.png">
> <img width="355" alt="Screenshot 2020-08-20 at 08 33 14" src="https://user-images.githubusercontent.com/10854265/90730349-e497b580-e2bf-11ea-84bf-6cde15a9d50c.png">
>
> NHS [does not use an external link icon](https://service-manual.nhs.uk/content/links) and suggest links should open in a new window only if you're logged into a secure area, such as an account
> 
> [Digital.NSW expect you to let the user where they're going](https://www.digital.nsw.gov.au/design-system/guides/writing-content/content-style-guide/using-links)
>
> [US Government has an external link icon](https://designsystem.digital.gov/typography/02-links/) but no research to underpin

**Comment by mrmjprice** [comment]
A mixed bag of examples, but only GOV.UK's designs seemed informed by research...

Do we need this?

**Comment by KaterinaKir** [comment]
Research shows that most people don’t understand the icon when they first see it, especially an external link icon. Visually, a lot of links with hyperlink cues are difficult to read because the icons could be distracting. Icon also interferes with page formatting.

Recommendation: Do not user external link icon. Link text should provide enough information to where the link will take them. For example, 'You can take the test on Hotjar.'
