### ISSUE TITLE
Ordered list and unordered list styling

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#326]
## What
> Ordered and unordered lists do not currently have a mention on the Design System
> 
> During the accessibility sprint, we faced issues with nested lists, where there are child lists of lists, particularly with the [Swift Terms and Conditions](https://www.networkwestmidlands.com/terms-conditions/swift-card).
> 
> Currently, the Design System can handle nested lists, but does not show counters:
> <img width="619" alt="Screenshot 2020-08-21 at 09 26 05" src="https://user-images.githubusercontent.com/10854265/90869588-5808f800-e390-11ea-9468-6704adade530.png">
> You would expect this screenshot to show 1. a. or something similar
>
> We need to define what nested lists look like

## Why
>- Terms and Conditions need a rewrite to make them understandable, but that could be a long way off
>- Terms and Conditions are a legal part of our website with legal clauses
>- We cannot change the clauses without legal redrafting the document

## Anything else
> [GOV.UK does not use nested lists](https://design-system.service.gov.uk/styles/typography/#lists)
> 
> ### Ordered lists
> IBM have different ways of doing ordered lists... [Carbon design system](https://www.carbondesignsystem.com/components/list/code/) only goes to 2nd level (1. and a.). Their [documentation](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.4.0/com.ibm.zos.v2r4.f54dt00/ordli.htm) goes to 4 levels.
> 
> If we don't do this, we could end up with less accessible content - CMS editors previously pasted word documents in which meant the numbering was in-text, rather than a structured list
> 
> [GOV.UK has an override class for adding space between list items - we should consider having this class available.](https://design-system.service.gov.uk/styles/typography/#lists)

**Comment by KaterinaKir** [comment]
Use numbered lists only when the sequence or count of items are important
* Unordered lists are used when the order of the items is not relevant. List items in unordered lists are marked with a bullet and from 2nd level hierarchy a dash is introduced. Hierarchy is shown with indentation as well.
* Ordered lists are used for sequential information and are enumerated. 
<img width="558" alt="Ordered nested list" src="https://user-images.githubusercontent.com/57525718/91157606-7424d600-e6bd-11ea-8c0a-7ce35a65aabd.png">
<img width="550" alt="Unordered nested list" src="https://user-images.githubusercontent.com/57525718/91157615-75560300-e6bd-11ea-8a1d-f5b224427206.png">

**Comment by KaterinaKir** [comment]
Component uploaded to Zeplin
