### ISSUE TITLE
Missing documentation on Content tiles component's page

### ISSUE THREAD

**Issue by catiarodriguescosta** [wmcadigital/wmn-design-system#347]
**Describe the bug**
Missing documentation on Content tiles component's page.
This information is not available on the provided documentation file.

**Comment by mrmjprice** [comment]
<details>
<summary>
My draft documentation
</summary>
# Content Tiles

## About
Content tiles are a method to visually contain components and text content. The component can be used in several ways. Some uses have been created as templates.

### Normal
#### General
##### What is it?
- A blank container for other components

##### When to use it
- When you need to group pieces of content together

##### When not to use it
- ???

#### General with one link
##### What is it?
- A content tile with a link to read more

##### When to use it
- When there are several content tiles on a page that are used for navigation
- When you need to give more information than just the title

##### When not to use it
- When you have more than one link in a content tile. Instead, you should use a Navigation content tile.
- When there is no descriptive text needed.

##### How to use it
- Titles should be descriptive enough to not need further explanation.
- Try to use active titles. For example, Get a Swift card.

#### Yellow modifier
##### What is it?
- An RTCC campaign branded content tile

##### When to use it
- When you are linking to major roadworks and events disruptions information.

##### When not to use it
- When you are trying to catch the user's attention other than for RTCC campaigns.
- For normal campaigns. Use the general content tile instead.

#### Yellow modifier
##### What is it?
- An RTCC campaign branded content tile

##### When to use it
- When you are linking to major roadworks and events disruptions information.

##### When not to use it
- When you are trying to catch the user's attention other than for RTCC campaigns.
- For normal campaigns. Use the general content tile instead.
</details>

**Comment by mrmjprice** [comment]
Linking in #362 #365 as connected...

Sorry for design decisions at the 11th hour. It was a debate and we thought it best to sort it now.

**Comment by mrmjprice** [comment]
<img width="1157" alt="Screenshot 2020-08-27 at 11 58 59" src="https://user-images.githubusercontent.com/10854265/91434420-b2a4c700-e85c-11ea-961f-569cc99ea882.png">

@gldgrnt - Please split out the page as shown in the image.

I will continue to work on my documentation.

**Comment by mrmjprice** [comment]
# Content cards (patterns)
## About
These are common applications of the content card component.
___

### Map card
#### What is it?
- A card with an interactive map component.

#### When to use it?
- When there is a user need for an interactive map to display information.
- When there is an alternative way to view the information on the interactive map.

#### When not to use it?
- When it is the sole way of presenting the information, you must provide an alternative.
- When the map is a screenshot or image. This is called a static map. Do not use static maps on West Midlands Network products.
- When there is no user need for a map, use text description instead.
___

### Travel update card
#### What is it?
- A card with disruption indicator components in, which show the live status of a bus, train or tram route and roads.

#### When to use it?
- When the live status of a mode of transport is useful to the content. For example, showing the live status of train lines next to content about trains.

#### When not to use it?
- When the live status is irrelevant to the content. Users can find this information on the homepage.
___

### Button card
#### What is it?
- A card with several buttons in.

#### When to use it?
- To direct users to different content relevant to their needs.
- At the end of the main page content. We found that users preferred to split lots of content into smaller, specific pages and that this was the best way to continue the journey after reading the main overview content. 

#### When not to use it?
- To attract the user's attention if there is no benefit to them reading the content.
- To list links within a section or related content. Use the in-line navigation card instead.
___

### Image card
#### What is it?
- A card with an image in.

#### When to use it?
- To display an image within a tile.
- When the image complements the text.

#### When not to use it?
- When the image has text in. This distracts the user and usually fails accessibility criteria.
- When the image is a cartoon or illustration. These are called vector images. Vector images display as poor quality for many users.
___

### In-line navigation card
#### What is it?
- A card with in-text links for navigation of sections and displaying related content.

#### When to use it?
- To help the user navigate a collection of pages. This is called a section.
- To show related content which meets user needs.
- To help the user navigate a long page using in-text anchors.
- Only use this pattern in a sidebar.

#### When not to use it?
- When the page links you are listing to form part of a journey or process. The journey should be linear.
- When you are trying to attract the user's attention. This is called a call-to-action.

#### How to use it
- The group of links must have a title to help users understand what the links are for. For example, 'Related content', 'On this page' or the section name.
- If the card is used to navigate a long page of content, it should be displayed on the left-hand side.
- If the card is used to navigate a set of pages, like a section or related content, it should be displayed on the right-hand side.
- The current page or section being viewed must be inset.
