### ISSUE TITLE
Add component page to icons

### ISSUE THREAD

**Issue by catiarodriguescosta** [wmcadigital/wmn-design-system#350]
**Describe the bug**
Page for icons component is missing.
Documentation already developed for this purpose.

**Comment by daylesalmon** [comment]
Closing this as it is a none-issue.

> Nice work!
> But I should of mentioned there is already an icons page: https://designsystem.wmnetwork.co.uk/styles/icons/
> 
> That's my bad :(

It relates to https://github.com/wmcadigital/wmn-design-system/pull/361 which I will also close as a none issue.
