### ISSUE TITLE
Form Elements Documentation

### ISSUE THREAD

**Issue by catiarodriguescosta** [wmcadigital/wmn-design-system#352]
**Describe the bug**
I'm checking if all component's text is updated. Inside form elements the first 2 elements does not have text associated (label, question, textarea, option bar, handling errors). Please close it if it is not an issue. 

https://designsystem.wmnetwork.co.uk/components/form-elements/

**Comment by mrmjprice** [comment]
@catiarodriguescosta The question element is defunct. We used ```<h2>``` in COVID-19 for heading hierarchy.

https://github.com/wmcadigital/wmn-covid19-directdebit/blob/master/src/components/Form/Step1TicketHolder/Step1TicketHolder.js

https://github.com/wmcadigital/wmn-covid19-directdebit/blob/ed453ad2fc9b0b1338a02def7316f9b50a6e0d34/src/components/shared/FormElements/Radios/Radios.js

@KaterinaKir - I don't know if this now needs to be updated in Sketch/Zeplin?

**Comment by daylesalmon** [comment]
@catiarodriguescosta can you update the "question" component from a h3 to a h2 please.

**Comment by mrmjprice** [comment]
# Form label
## What does it do?
* Tells users what a field is for.

## When to use it?
* When you are requesting multiple pieces of information to answer the same question. For example, the day, month and year of a date.
* The label must appear directly above the field.

## When not to use it?
* Do not use this component to ask more questions within a question - instead, ask a new question.
* When you're giving extra information and hints to help the user answer a question.

**Comment by mrmjprice** [comment]
# Question
## What does it do?
- Asks the user a question about information the service needs.

## When to use it?
- When you are asking users for information as part of a service.

## When not to use it?
- When it's not part of a service.
- When there are multiple questions on the same page, unless you have user research that says it makes sense to group the question?

## How it works
- Always test questions with users through user research
- Make sure your [question makes sense](https://www.gov.uk/service-manual/design/designing-good-questions)
- Sometimes it makes sense to group a few questions on the same page
- Make sure users know why you're asking the question and only ask users for information you really need
- Add (optional) to the end of each question that is optional

**Comment by catiarodriguescosta** [comment]
Thanks guys, will update the documentation and change h3 to h2 too. 

What about textarea, option bar, handling errors?

**Comment by mrmjprice** [comment]
Ah, didn't catch those. Will write something for those as well.

**Comment by mrmjprice** [comment]
# Text Area

## What does it do?
- Allows users to enter more than one line of text.
- Allows users to write whatever they like, also called free text.

## When to use it?
- When the user needs to enter lots of text. For example, a paragraph.

## When not to use it?
- When the user needs to enter one line of text. Use the input component instead.
- Use fixed-width inputs for content that has a known length, e.g. postcode.
- When there are limited options. Use a different form element that limits the options.

**Comment by mrmjprice** [comment]
# Option bar

We're going to retire this, as it's not been used and is a bit retro compared to our other patterns. If needed later down the line, we can reverse this decision. Please can you make sure it's a single commit in case we revert it down the line.

**Comment by mrmjprice** [comment]
# Handling errors
## What does it do?
- Lets the user know what is wrong with their answer.
- Tells the user how to correct their answer.
- Tells the user what format or characters it is expecting.
- Prevents the user from trying to submit information that will be rejected by the API.

## When to use it?
- A handling error is used in addition to an error summary, which shows all errors on a page.
- When there has been an error with validating the user's answer after they try to continue to the next step.
- When the error is a validation error that is fixable.
- Use a separate error for each group of answer fields. For example, one error for date fields.
- The corrective action should be read by a screen reader before data entry components.

## When not to use it?
- Do not show the error until the user tries to move to the next step. Immediate validation can distract a user from progressing, especially if it validates as the user is typing.
- Hint text should help the user to understand how the field will be validated.
- If the service is down the user should be shown a service unavailable page.

## How to use it
- Make sure questions and help text are well designed and tested with users to avoid errors in the first place.
- GOV.UK has advice to follow when [writing error messages](https://design-system.service.gov.uk/components/error-message/)
- GOV.UK has advice for [helping users to recover from validation errors](https://design-system.service.gov.uk/patterns/validation/).

**Comment by mrmjprice** [comment]
@catiarodriguescosta Hopefully these are all done now?

**Comment by catiarodriguescosta** [comment]
@mrmjprice will do that in a single commit! 
Will update this in the meanwhile! :) Thanks!
