### ISSUE TITLE
General/Yellow Modifier/Major Works content tiles should not have 'Read more' links.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#362]
**Describe the bug**
The General/Yellow Modifier/Major Works content tiles should not have a 'Read more' link in the bottom right of the tile.

**Expected behaviour**
The entire content tile should be clickable, making the 'Read more' link redundant.

See Zeplin for updated content tile designs.

**Additional context**
- The 'General with one link' component can be removed entirely as it is no longer necessary.
- Nav link content blocks should remain the same and not be changed.

**Comment by mrmjprice** [comment]
#365 #347 connected
