### ISSUE TITLE
Add an Image Content Tile to the Content Tiles component section.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#365]
## What
> Add a new content tile with an image above the heading into the Content Tiles component section of the Design System.

## Why
> To give content editors the option to add decorative images to content tiles.

## Anything else
> Content Tile Image Design is in Zeplin, under Content Tiles section.
![Screenshot 2020-08-26 at 14 28 16](https://user-images.githubusercontent.com/62507489/91309350-639d5a00-e7a8-11ea-89f9-2bc94925ed50.png)

**Comment by mrmjprice** [comment]
Connected with #347 and #362
