### ISSUE TITLE
Update header in the Header and footer pattern.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#366]
## What
> Header in the Design System can be updated with the newly designed header.

## Why
> The header has been tested with users and re-designed based on the recommendations from the user testing.

## Documentation
> Add in the 'Navigation' section after the second paragraph: For desktop, the megamenu will appear when a user hovers over a top-level navigation title, with the colour behind the selected option changing to Secondary Purple when active. For tablet and mobile devices, the megamenu will appear when a top-level navigation title has been tapped.
> Add in the 'With a title variant of header' section after the first paragraph: Further optimisation and testing will be done to this variant, which may cause the design to change in the future.

## Anything else
> Designs are in Zeplin
> The phase indicator banner and breadcrumbs should remain in the same place. It's only the header banner which requires changing.
> Houston is currently working on adding the header with megamenu dropdown in the Design System.

![Screenshot 2020-08-26 at 15 07 46](https://user-images.githubusercontent.com/62507489/91313961-ea086a80-e7ad-11ea-8520-2737a409c96d.png)

**Comment by mrmjprice** [comment]
https://github.com/wmcadigital/wmn-sprints/issues/25

**Comment by houbly** [comment]
This has now been merged into the design system
