### ISSUE TITLE
Change navigation link underline in the Design System header and footer.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#367]
**Describe the bug**
The navigation links in the Design System header and footer should not have an underline text style unless a user hovers over a link. 

**Expected behaviour**
The underlined text style on the navigation links should only be shown on hover.

The user testing found users preferred main navigation links without an underline. This will need to be changed in the Design System header and footer to match the new site-wide header & megamenu.

**Comment by mrmjprice** [comment]
https://github.com/wmcadigital/wmn-sprints/issues/25

**Comment by daylesalmon** [comment]
Assigned to @houbly as this will naturally be fixed with the new header/footer patterns.
