### ISSUE TITLE
Move 'Progress Indicator' from the Patterns page, to the Components page.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#370]
**Describe the bug**
Progress Indicator is a component, not a pattern.

**Expected behavior**
The 'Progress Indicator' page should be moved to the Components section.

**Comment by daylesalmon** [comment]
Can this be moved to the from components section.

**Comment by jkmnch** [comment]
Yes, the progress indicator can be moved into the 'Form elements' section.
