### ISSUE TITLE
Add images documentation to styles section 

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-design-system#397]
Images
 
**What does it do?**

- An image tells a story, communicates a complex idea or supports page content by providing further details.

**When to use it?**

- When there is a clear user need.
- When an image serves a clear functional purpose.
- All images, except decorative, must have alt text that describes the content and function of the image. This tells users using screen readers what information the image provides.

**When not to use it?**

- When an image is an unnecessary decoration.
- When an image would create visual noise, which detracts attention away from the page content. This can distract the user from completing their task.

**Comment by gldgrnt** [comment]
@KaterinaKir Should we provide image examples to go with the documentation?

**Comment by KaterinaKir** [comment]
@gldgrnt I think it is not necessary because we have brand guidelines that go into details on how to use images. We can add a to brand guidelines (but it is a pdf) https://wmca.assetbank-server.com/assetbank-wmca/action/viewAsset?id=134&index=0&total=1&view=viewSearchItem

**Comment by gldgrnt** [comment]
Yeah? I could add a sentence with a link to it?

**Comment by KaterinaKir** [comment]
Yes, please add a sentence with a link. E.g For more guidance on how to use images, please check WMN brand guidelines.
