### ISSUE TITLE
Correct styling of Default link on links page

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#41]
Change to CTA blue, bold with an underline. Current default link displays like an unstyled block of purple.

<img width="287" alt="Screenshot 2019-11-27 at 10 26 34" src="https://user-images.githubusercontent.com/10854265/69715584-74794c00-1100-11ea-96c0-0274d50bbd50.png">

**Comment by daylesalmon** [comment]
This was fixed in https://github.com/wmcadigital/wmn-design-system/commit/3a1a22274d009c22292573c7d6633f7200393d88
