### ISSUE TITLE
When you click an accordion, the text on the accordion blinks

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#452]
When you click to expand or collapse an accordion, the text on the accordion blinks for a split second.

Is there any way we can stop this?

![Screen-Recording-2020-10-16-at-1](https://user-images.githubusercontent.com/10854265/96265983-06f73800-0fbe-11eb-89ee-5241e9764727.gif)

**Comment by houbly** [comment]
@mrmjprice how can I replicate this? I'm not seeing where this happens in the design system

**Comment by mrmjprice** [comment]
Safari Version 14.0 (15610.1.28.1.9, 15610)

https://deploy-preview-450--wmnetwork.netlify.app/styles/a-to-z-content-style-guide/

If you click and hold an accordion, the text will disappear.

Or if you navigate by keyboard to the accordion control, holding down space, the text will disappear.
