### ISSUE TITLE
Issue on existing Swift templates

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#453]
Mobile header nav on https://www.networkwestmidlands.com/swift

West Midlands Network logo is clipped.

Please can this be fixed on the existing site via a CAB?

<img width="573" alt="Screenshot 2020-10-19 at 08 25 23" src="https://user-images.githubusercontent.com/10854265/96414212-b6155880-11e4-11eb-829a-b36981b6d3f6.png">

<img width="574" alt="Screenshot 2020-10-19 at 08 25 33" src="https://user-images.githubusercontent.com/10854265/96414204-b31a6800-11e4-11eb-8f66-b6e9178cfa1f.png">

**Comment by mrmjprice** [comment]
Please can you let me know when this will go live, so I can inform the brand consultant? :smile:

**Comment by houbly** [comment]
@mrmjprice this issue is fixed on staging here: https://stagenwm.cenapps.org.uk/swift I'll need help from @daylesalmon to move the css into the right place but its essentially ready.

**Comment by mrmjprice** [comment]
Thanks, @houbly.

I've let the stakeholder know that it'll be in the next week. 😄

**Comment by houbly** [comment]
@mrmjprice this change has gone live now
