### ISSUE TITLE
Font size on mobile

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-design-system#460]
Please update font size of 'Resources & Support' and 'About us' to match 'Stay up to date' (23 px) on the mobile version. At the moment on the mobile it shrinks to 16px (body copy)

![IMG_3550](https://user-images.githubusercontent.com/57525718/96846216-81eea180-1449-11eb-8328-a90395231d64.PNG)

**Comment by jkmnch** [comment]
@houbly I will re-design the mobile footer with the correct font size in Sketch first, and then I'll upload it into Zeplin for you. I'll post the Zeplin link here when It's uploaded.

**Comment by jkmnch** [comment]
@houbly Update footer with correct heading size now in Zeplin under Header and Footer: https://app.zeplin.io/styleguide/5d95b0aaad77af16c796a476/components?cseid=5d9af5013c867b1e2d05e8ca
