### ISSUE TITLE
Mobile navigation headers

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-design-system#463]
Mobile header: when user selects first level navigation item, e.g. Swift and tickets or Get help, at the top of next screen it should show that title, e.g. Swift and tickets. At the moment it shows Plan a journey for all options. 

<img width="501" alt="Screenshot 2020-10-22 at 09 38 33" src="https://user-images.githubusercontent.com/57525718/96847117-b6169200-144a-11eb-9a6c-075491837282.png">

<img width="494" alt="Screenshot 2020-10-22 at 09 38 21" src="https://user-images.githubusercontent.com/57525718/96847120-b6af2880-144a-11eb-8d4a-cfdaf5b9b1d0.png">

**Comment by houbly** [comment]
Sorry @KaterinaKir this one was an oversight on my part, I'll fix this directly in Umbraco

**Comment by KaterinaKir** [comment]
No worries, thank you
