### ISSUE TITLE
OneApp Bike Hire- New eBike Icon

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#474]
[Beryl 301020LS Map Assets.zip](https://github.com/wmcadigital/wmn-design-system/files/5476568/Beryl.301020LS.Map.Assets.zip)
![Pin - Cycle - x bikes available@2x](https://user-images.githubusercontent.com/61703409/97721481-5f036380-1ac1-11eb-8f10-41b84e534a88.png)

## What
Swift is working on integrating a new bike hire proposition into the OneApp. To do this, Swift is working with Beryl who provide the bike hire technology and also the cycling team from a strategy and delivery perspective. 

As part of the integration into OneApp, we are using iconography to illustrate the bike bay location on a map. We now need to create an additional icon which will illustrate that eBikes are available at a bike hire location. 

The recommendation from Beryl (who already have iconography for this) is to use a lightening bolt symbol within the icon. 

## Why
Given that this is new territory and there is not existing iconography for this we require design input and would recommend adding this into the design system for WMCA colleagues to access. This will ensure consistent application of  displaying eBikes across WMCA touchpoints.
>
> - What evidence do you have that it's needed by multiple services across government? Only that we have a cycling team and they use other touchpoints outside of OneApp.
> - What evidence do you have that it meets the needs of the users of those services? The iconography is already being used by Beryl who have a customer base.
> - Have you checked that it doesn't already exist in the WMN DS? Yes
![OneApp_Bike_Hire_Integration](https://user-images.githubusercontent.com/61703409/97703833-33747f00-1aa9-11eb-94a4-0cd4244be477.png)
![Screenshot_20201030-094825](https://user-images.githubusercontent.com/61703409/97703848-3b342380-1aa9-11eb-803a-7c1633659b0a.jpg)

## Anything else
> Include links to any examples, research or code to support your proposal, if available.
I have attached:
Example of the cycling icon to be used when no eBikes are available
Example of the cycing icon with eBikes that Beryl currently use in their app
Wireframe user testing: https://app.maze.design/projects/19525687/mazes/19525664/results

**Comment by samanthabinns** [comment]
Can you let me know rough timescales for this, so I can let the project team know?

**Comment by KaterinaKir** [comment]
Hi @samanthabinns I will add this request to our next sprint which will start on November 9. I estimate that it will take around 1 day to complete.

**Comment by samanthabinns** [comment]
@KaterinaKir please note that I have now added the assets you requested.

**Comment by jkmnch** [comment]
Hi @samanthabinns I have designed 4 different eBike icons for your review. Two icons contain the lighting bolt symbol within the bike icon itself and two where the lightning bolt icon is placed in the top right of the green container. We need to use a white background behind the lightning bolt symbol as the blue and green together do not meet colour contrast requirements for graphical requirements, which will cause issues for users who have visual impairments. Please let us know which icon you prefer.

Icons ZIP file: [eBike-Icons.zip](https://github.com/wmcadigital/wmn-design-system/files/5509816/eBike-Icons.zip)

We have not decided to use the same approach as Beryl and place the lightning bolt symbol outside the corner of the bike indicator, as we don't have any mode icons in this style in the Design System. We would prefer to keep the lightning bolt symbol within the green container to maintain conformity across the Design System.

I am looking to add a new colour into the Design System named 'Electric modes'. This new colour is currently used for the lightning bolt symbol in the icons I've provided. I wanted to create a separate colour in case we need to add more electric modes in the future (e.g. electric cars for hire). Creating a new colour also means we do not have to use colours reserved for other actions or modes, such as the Call-to-action button blue or tram blue.

**Comment by jkmnch** [comment]
@samanthabinns Also, do you know the dimensions of the current icons in the OneApp? It'll be nice to have them so I can design the new icons in the correct size

**Comment by samanthabinns** [comment]
Hi Jake,

Thanks for providing these options. Can we go with eBike-3? Re dimensions, can you use the dimensions of the cycle icon attached (Beryl 301020LS Map Assets.zip)? That's the icon we are using in the app and should be correct dimensions.

Can you also advise

**Comment by jkmnch** [comment]
@samanthabinns Please see attached the Closed station pin, eBike pin and eBike icon (on its own) as SVGs: 
[OneApp-Icons.zip](https://github.com/wmcadigital/wmn-design-system/files/5511373/OneApp-Icons.zip)

These pins/icons are not yet on the Design System site. I will submit a new feature request to the developers to add the new pins/icons onto the Design System site. 

I've resized the pins to the same dimensions as the Beryl pins you sent, so they should be correct. But please let me know if there are any issues and I can amend them.

**Comment by samanthabinns** [comment]
That's great, thank you @jkmnch. I've shared the assets with our supplier, I'll let you know if we need resizing.

**Comment by samanthabinns** [comment]
@KaterinaKir you can close this ticket.
