### ISSUE TITLE
Swift- Bike Hire Integration- Out of use station icon

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#483]
## What
Swift is working on integrating a new bike hire proposition into the OneApp. To do this, Swift is working with Beryl who provide the bike hire technology and also the cycling team from a strategy and delivery perspective.

As part of the integration into OneApp, we are using iconography to illustrate the bike bay location on a map. It has recently been brought to our attention that within the data feed we will have visibility of out of use stations. We need a way to visually represent this on the map alongside other bay locations.

Context on when out of use stations are used:
Following from the below, I had a chat with the Beryl team about the sorts of situations that cause a station to be disabled. Apparently it is pretty rare, but it is typically either due to something like a road closure, or they have a selection of stations that are event specific e.g. docks at football stadiums that only operate on matchdays. We don’t receive any data in the feed to determine why a station is disabled, or when it might be coming back – however, the suggestion would be for the WMCA team to update the “Dock name” field if they’re closing a dock, to indicate more useful information on a case by case basis e.g. call the dock “NEC West (Event Days Only)” or “Acacia Lane (Closed due to roadworks until 23/5/21)” etc. This means we wouldn’t have to add any other UX complexity in One App other than the changed icon. A list of known closures/issues could also be added to the “More information” page accessible from the tray (another action for the cycle team).

## Why
Given that this is new territory and there is not existing iconography for this we require design input and would recommend adding this into the design system for WMCA colleagues to access. This will ensure consistent application of displaying eBikes across WMCA touchpoints.
>
> - What evidence do you have that it's needed by multiple services across government? Only that we have a cycling team and they use other touchpoints outside of OneApp.
> - What evidence do you have that it meets the needs of the users of those services? None
> - Have you checked that it doesn't already exist in the WMN DS? Yes

## Anything else
> Include links to any examples, research or code to support your proposal, if available.
 
Examples of out of service stations from Beryl.

[E-bike App Visuals (LS051120).zip](https://github.com/wmcadigital/wmn-design-system/files/5500188/E-bike.App.Visuals.LS051120.zip)

**Comment by samanthabinns** [comment]
@KaterinaKir can you let me know whether this can go into the next week's sprint?

**Comment by KaterinaKir** [comment]
@samanthabinns, yes this can go to next week's sprint. Thanks

**Comment by samanthabinns** [comment]
That's great, thank you @KaterinaKir

**Comment by samanthabinns** [comment]
@KaterinaKir you can close this ticket.
