### ISSUE TITLE
Change the Search function description in the Header V2 pattern page on the Design System site

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#491]
## What
> Change the Search function description in the Header V2 pattern page on the Design System site.

## Why
> We need to update the description under the **Search** heading on the 'Header V2' pattern page with details on the new 'I want to...' feature.

**Current description:**
![Screenshot 2020-11-11 at 14 01 11](https://user-images.githubusercontent.com/62507489/98820668-5d715e00-2426-11eb-87ec-632660f38868.png)

Change it to:

#### Search
This function expands the mega menu and reveals the search bar along with the ‘I want to…’ feature. 

The ‘I want to…’ feature shows a list of the top page links which users access through search. This is to help users find the information they are searching for faster. These links are regularly updated using search data to maintain their relevance.

On mobile, the mega menu search function uses a primary purple background instead of the standard white background. Our user testing found users preferred the white link text on the primary purple background as it is clearer to read.

**Comment by houbly** [comment]
This update is now live
