### ISSUE TITLE
Swift OneApp- Screenshots for App Store

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#495]
I need some screenshot assets created to build the app store profile for OneApp.

The screenshots will show in the app stores for Google Play & Apple. When a customer searches for the app and they click to view more information these screenshots will show to highlight key features of the app.

I have attached examples of what the screenshots should look like. 

I need 5 assets to be created and have attached the images for you to use too:

1.	HP logged in screenshot (edit customer logged in name to a generic customer name)
Copy: Everything you need to travel around the West Midlands.
Image: HP_LoggedIn_Screenshot
2.	Login screenshot 
Copy: Login and manage your Swift account anytime and anywhere.
Image: Login_Screenshot
3.	Nearby screenshot with bus filter applied
Copy: Use the Nearby map to locate your closest mode of transport.
Image: Nearby_Map_Screenshot_Bus_Filter
4.	Train Departure board screenshot 
Copy: View the latest departure information for bus, train and tram.
Image: Nearby_Map_Screenshot_Train_Departures
5.	My tickets screenshot (edit require, remove 'update' button in top right)
Copy: Quickly view your active and expired tickets
Image: My_Tickets_Screenshot

Asset Dimensions:
Apple App Store: 1242x2688 or 2688x1242 or 1284x2778 or 2778x1284 px
Google Play Store: JPEG or 24-bit PNG (no alpha)
Minimum dimension: 320px
Maximum dimension: 3840px
The maximum dimension of your screenshot can't be more than twice as long as the minimum dimension.

Please let me know if you have any queries and the timeline to complete this.

![Nearby_Map_Screenshot_Bus_Filter](https://user-images.githubusercontent.com/61703409/99065589-88cb8880-259f-11eb-8c98-08b723268535.png)
![Nearby_Map_Screenshot_Train_Departures](https://user-images.githubusercontent.com/61703409/99065597-8bc67900-259f-11eb-8148-67a706eea05f.png)
![HP_LoggedIn_Screenshot](https://user-images.githubusercontent.com/61703409/99065603-8e28d300-259f-11eb-9d16-ae9ea9a0e082.png)
![Login_Screenshot](https://user-images.githubusercontent.com/61703409/99065611-8f5a0000-259f-11eb-9a17-37cc2fde90c8.png)
![My_Tickets_Screenshot](https://user-images.githubusercontent.com/61703409/99065613-908b2d00-259f-11eb-9820-18746499c442.png)

![App_Store_Login_Screenshot](https://user-images.githubusercontent.com/61703409/99066178-6d14b200-25a0-11eb-9300-8ead9f7cb2b7.jpg)
![App_Store_Nearby_Screenshot](https://user-images.githubusercontent.com/61703409/99066184-700fa280-25a0-11eb-9d8d-22f658672a9c.jpg)
![App_Store_Wallet_Screenshot](https://user-images.githubusercontent.com/61703409/99066190-7140cf80-25a0-11eb-998d-3a0593326766.jpg)
![App_Store_Departure_Screenshot](https://user-images.githubusercontent.com/61703409/99066195-730a9300-25a0-11eb-9fc1-8d8341b11f03.jpg)
![App_Store_HP_Screenshot](https://user-images.githubusercontent.com/61703409/99066198-743bc000-25a0-11eb-8ba5-4f053cc19fe2.jpg)

**Comment by samanthabinns** [comment]
Thanks for sharing @jkmnch and for providing options on branding. Can you use the secondary purple? I agree the screenshots need more contrast with the background and the primary purple makes that difficult to achieve.

I have some feedback which is as follows:
- The screenshots look pixelated, is there anything you can do about that? Do you think it will look pixelated in the app store?
- Home page can you edit the customer name to something more generic?
- My tickets page can you edit out 'update' button? This is only there in staging and will not be there in live so I'd like it removed

**Comment by jkmnch** [comment]
@samanthabinns Hi Sam, thanks for the feedback. I've made the changes you requested to both Apple App Store and Google Play Store images.

Download: 
[App Store Images.zip](https://github.com/wmcadigital/wmn-design-system/files/5566027/App.Store.Images.zip)

The screenshots aren't pixellated on my or Kat's laptop. They're high quality for us, even when zoomed in. Could this be an issue with your computer/monitor that is causing the pixelation?

Also, I've designed the Google Play Store images at 1497x2658px resolution. I chose this size by looking at other app images to see what their resolution was.

**Comment by samanthabinns** [comment]
@jkmnch  thanks for making those changes. Re pixelated, it could be my screen, should be fine if it displays correctly on both of yours.

Thank you for the assets, I am happy with these. I will let you know if there are any issues with the dimensions when uploading to the stores.

**Comment by samanthabinns** [comment]
@KaterinaKir You can close this ticket.

**Comment by KaterinaKir** [comment]
Thanks
