### ISSUE TITLE
'Styles' and 'Patterns' read more links in the content cards on the Design System homepage are aligned to the right

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#504]
As the title describes, the read more links for the Styles and Patterns are aligned to the right of the content card container.

The links should be aligned to the left of the content card, so they are the same as the User Research and Components cards.

![Screenshot 2020-11-20 at 09 21 02](https://user-images.githubusercontent.com/62507489/99783008-c4230580-2b11-11eb-92a5-09c55f817a45.png)

**Comment by houbly** [comment]
This update is now live
