### ISSUE TITLE
Change phase indicator from <a> tags to <span> tags to remove link

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#508]
https://designsystem.wmnetwork.co.uk/components/phase-indicator/

Currently, it's a link, but I'm not sure that it needs to be.

We could just change it so it's in ```<span>``` tags rather than ```<a>``` tags, which would remove the link, but maintain the styling.

**Comment by KaterinaKir** [comment]
@mrmjprice We do not use it as a link on live service, therefore feel free to remove a tags.

**Comment by jkmnch** [comment]
@mrmjprice I'm happy for the link to be removed from the indicator.
