### ISSUE TITLE
json data being overwritten becuse of 2 files doing the same thing?

### ISSUE THREAD

**Issue by rolorogan** [wmcadigital/wmn-design-system#522]
There's 2 files which have the same data. Becuse of this the version that is built is a combination of both files. So if you e.g. remove a colour in one, then it won't be removed becuse it's in the other.

- wmn-design-system/src/www/data.njk.json
- wmn-design-system/src/www/assets/json/merged.njk.json

**Comment by daylesalmon** [comment]
@rolorogan this is due to be fixed in: #524
