### ISSUE TITLE
A-to-z content style guide

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#527]
An issue to keep hold of any suggested additions or changes for the [A-to-Z content style guide](https://designsystem.wmnetwork.co.uk/styles/a-to-z-content-style-guide/)

**Comment by mrmjprice** [comment]
Suggest to add entries for:
- rail zones/train zones
- app/mobile app/mobile application
- iOS/iPhone
- Apple App Store/iOS App Store/App Store
- Android App Store/Google Play Store

**Comment by daylesalmon** [comment]
This has been fixed and merged in to release.
