### ISSUE TITLE
OneApp- Apple Screenshots Resize

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#532]
Can you resize the OneApp Apple screenshots to 1242 x 2208. I have attached the assets.

Can you get this across today please?
[App.Store.Screenshots.FINAL.zip](https://github.com/wmcadigital/wmn-design-system/files/5695538/App.Store.Screenshots.FINAL.zip)
[App.Store.Screenshots.FINAL.zip](https://github.com/wmcadigital/wmn-design-system/files/5695541/App.Store.Screenshots.FINAL.zip)

## What
> Give a brief description of the style, component or pattern you want to propose.

## Why
> Explain why you think this should be added to the West Midlands Network Design System (WMN DS).
>
> - What evidence do you have that it's needed by multiple services across government?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the WMN DS? 

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

**Comment by jkmnch** [comment]
@samanthabinns Hi Sam, I've resized the Apple App Store images to 1242 x 2208. I've had to make the iPhone mockups smaller in size, to fit the reduced height.

Download: [Apple App Store.zip](https://github.com/wmcadigital/wmn-design-system/files/5695831/Apple.App.Store.zip)

Let me know if you have an issues.

**Comment by samanthabinns** [comment]
That's great. Thank you @jkmnch. I'll let you know if any issues.
