### ISSUE TITLE
Formatting for Dates in mobile view

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#631]
Can we get the date optimised for mobile? I feel the current formatting is quite long in mobile view.

We are working on a statement for the Swift account section and the design would benefit from a shortened date format.
For example
3 Jan 2021
02/02/2021
Tues 2 Jan

Examples below.
![image](https://user-images.githubusercontent.com/61703409/106875457-99872880-66ce-11eb-9dc3-9ea7a1972586.png)

![image](https://user-images.githubusercontent.com/61703409/106875540-aefc5280-66ce-11eb-9cc0-98aba37adef2.png)

**Comment by daylesalmon** [comment]
Thanks for submitting this @samanthabinns!

It is perfectly acceptable to use the shorthand date format "3 Jan 2021" when limited by space as mentioned in the [dates style guide](https://designsystem.wmnetwork.co.uk/styles/a-to-z-content-style-guide/#dates).

Have a quick look over the [dates style guide](https://designsystem.wmnetwork.co.uk/styles/a-to-z-content-style-guide/#dates) and see if it helps solve your problem. If you are still having difficulty then come back to us 😄 .

I'd also recommend checking the [A to Z content style guide](https://designsystem.wmnetwork.co.uk/styles/a-to-z-content-style-guide/#dates) if you run in to similar issues where you are unsure of how content should be displayed to the user.

I hope this helps!

**Comment by samanthabinns** [comment]
thanks @daylesalmon think I missed that bullet point. I'll progress with that guidance. Happy for you to close the ticket.
