### ISSUE TITLE
eScooter assets

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#708]
- [x] Add icon and brand mark
- [x] Add to Travel Mode banner too with green background

Assets to follow.

**Comment by mrmjprice** [comment]
@jkmnch - This will need adding to the Sketch file too

**Comment by mrmjprice** [comment]
[WM eScooter.zip](https://github.com/wmcadigital/wmn-design-system/files/6212642/WM.eScooter.zip)

**Comment by jkmnch** [comment]
@mrmjprice Done :)
