### ISSUE TITLE
Add number input to the Design System form elements

### ISSUE THREAD

**Issue by gldgrnt** [wmcadigital/wmn-design-system#746]
## What
The new roads disruptions contain a search radius input that isn't currently in the design system.

## Why
So that it can be used across the disruption apps.

## Anything else
Example:

![image](https://user-images.githubusercontent.com/43111519/116096474-3db2b700-a6a1-11eb-89c2-cd3e0627b26d.png)

## Documentation 
What does it do?

- Allows users to increase or reduce search radius (in miles)

When to use it?
- When user needs to define a radius 

When not use it?

- When user needs to enter location, postcode or place of interest 

How it works?

- When user clicks minus button, radius reduces by 1 mile, when user clicks plus button, radius increases by 1 mile
- Default radius is always 3 miles because research shows that most of the journeys in West Midlands are within 3 miles.

**Comment by gldgrnt** [comment]
@KaterinaKir I was thinking that it might be better for this to be a generic number input rather than a search radius specific component. Just because, from a dev perspective, the value we get from it is just a number and not tied to any specific units.

**Comment by KaterinaKir** [comment]
Hi @gldgrnt, please see updated documentation: 

Number Imput

What does it do?
* Allows users to select a number by increasing or reducing it incrementally
When to use it?
* When user needs to select and adjust a number incrementally
When not use it?
* When user needs to enter information other than a number, for example location, postcode or place of interest
How it works?
* When user clicks minus button, number reduces by 1, when user clicks plus button, number increases by 1 mile
