### ISSUE TITLE
Unsafe attempt to load URL URL/TO/SVG.svg. Domains, protocols and ports must match.

### ISSUE THREAD

**Issue by rolorogan** [wmcadigital/wmn-design-system#76]
**Describe the bug**
When using any components with SVG links it errors when not on the same domain:

**Unsafe attempt to load URL http://wmnetwork.netlify.com/img/svg-sprite.min.svg from frame with URL http://localhost:3000/index.html. Domains, protocols and ports must match.**

This is a security issue, because a SVG is XML, and you can’t load a XML file from different locations.

**To Reproduce**
1. Link <link href="//wmnetwork.netlify.com/css/wmnds-components.min.css" rel="stylesheet" type="text/css" ><link href="//wmnetwork.netlify.com/css/wmnds-website.min.css" rel="stylesheet" type="text/css" > to a local html file.
2. Add any design component with an svg link
3. SVG will not load and display
4. See error in console

**Expected behavior**
SVG loads

**Additional context**
More info:
 - https://bugs.chromium.org/p/chromium/issues/detail?id=470601
 - https://medium.com/the-ui-files/load-svgs-from-different-domains-ports-protocols-1614e1af6101

**Comment by daylesalmon** [comment]
New build coming up to fix the file name so it can be downloaded and used locally.
