### ISSUE TITLE
Travel updates widget: Needs smaller disruption indicators and reduced white space on mobile

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-design-system#787]
## Disruption indicators

The current disruption indicator sizes are Medium. This widget will need to use the Small [disruption indicators](https://designsystem.wmnetwork.co.uk/components/disruption-indicators/) instead. Please update on both mobile and desktop. Also, please reduce white space between items to optimise it so users don't have to scroll too much. At the moment gaps are quite large. 

<img width="496" alt="Screenshot 2021-05-20 at 12 53 14" src="https://user-images.githubusercontent.com/57525718/118974170-6cebd980-b96a-11eb-8983-ab775a9ca09c.png">

Here are the designs if you need them: https://www.figma.com/file/rQRpNn6RM6nUcbm2HCWQlO/WMN-Design-System?node-id=0%3A5459

## Disruption link text

Mobile / break points

The disruption link text in the travel updates widget moves onto a new line when the screen size is 567px. This is an issue as there is still room for the disruption link text on the right side of the widget, so it makes the widget longer than it needs to be.

Since we will be using the smaller disruption indicators, the breakpoint for disruption link text will need to be changed when the screen size reaches 392px.

**Comment by catiarodriguescosta** [comment]
This will be fixed in umbraco for now as it was too tight to resolve it here before the release time (20min ago).
Anyway, it will be updated as soon as we can, as it is not urgent anymore.
