### ISSUE TITLE
Buttons layout

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-design-system#791]
Please stack buttons in JP on very small screens where they do not fit, like you did for travel updates. Screenshots attached.

<img width="480" alt="Screenshot 2021-05-18 at 09 46 12" src="https://user-images.githubusercontent.com/57525718/118621219-117ce880-b7be-11eb-972f-396e60476290.png">
<img width="434" alt="Screenshot 2021-05-18 at 09 46 18" src="https://user-images.githubusercontent.com/57525718/118621224-12ae1580-b7be-11eb-9525-01fa55e6750f.png">

**Comment by catiarodriguescosta** [comment]
This one is fixed already. Just need to release it to the dev env. 👍
