### ISSUE TITLE
Pay with Swift button

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-design-system#807]
## What

> A variant of the primary button that allows users to pay for things with their Swift account. This will be used on third party transport apps, for example Beryl.

## Why

> Explain why you think this should be added to the Transport for West Midlands Design System (TfWM DS).
> Users should have a consistent way of starting a payment through their Swift account.
> - What evidence do you have that it's needed by multiple services across government?
It's needed by private companies who are delivering services on behalf of TfWM.
> - What evidence do you have that it meets the needs of the users of those services?
N/A
> - Have you checked that it doesn't already exist in the TfWM DS?
It is a variant of an existing button
## Anything else

> Include links to any examples, research or code to support your proposal, if available.
[Beryl app prototype w/ button included](https://www.figma.com/proto/nVBvG9U8gWtAVxVILwq4sm/Beryl-app-prototype-Swift-pay-button?page-id=138%3A4669&node-id=142%3A2733&viewport=1089%2C375%2C0.03761913999915123&scaling=scale-down)

**What does it do?**

- Starts the process of paying for something with a Swift account

**When to use it?**

- When a button starts a payment process using a Swift account

**When not to use it?**

- For other actions involving a Swift account, for example topping up a balance

**Comment by KaterinaKir** [comment]
Here is button design. CTA blue with swift logo

![Button](https://user-images.githubusercontent.com/57525718/119977687-a8ad2180-bfb0-11eb-82ac-edda6252fa82.png)

**Comment by catiarodriguescosta** [comment]
Hi all, 
I will close this one because it is repeated (https://github.com/wmcadigital/wmn-design-system/issues/825) and there's already an open pull request for it. :)
Thanks!
