### ISSUE TITLE
Set content card image to 170px 

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-design-system#808]
Set content card image to 170px so the height is always consistent. 

**Example**
<img width="380" alt="Screenshot 2021-06-01 at 08 26 28" src="https://user-images.githubusercontent.com/57525718/120288622-5291f400-c2b8-11eb-9e10-c501736db7a8.png">

Martin advised that at the moment it is 100% width, matched the aspect ratio of the image. Therefore we can get narrow images like this (but ideally we want to avoid it).

<img width="335" alt="Screenshot 2021-05-28 at 13 36 59" src="https://user-images.githubusercontent.com/57525718/120288738-75bca380-c2b8-11eb-81eb-7b47445a8da5.png">

**Comment by catiarodriguescosta** [comment]
Hey Kat, 
I believe this is now avoidable in Umbraco with the crop feature added by Dayle.
Do you want to proceed with this change in the design system?

**Comment by houbly** [comment]
Closed as this is fixed in Umbraco
