### ISSUE TITLE
Button text alignment

### ISSUE THREAD

**Issue by houbly** [wmcadigital/wmn-design-system#821]
The .wmnds-text-align-{position} class isn't specific enough to be used to align buttons to the left/right when icons are used. Also when text wraps to a second line the layout (icon size/position) is inconsistent so we may need to add a consistent way to cover both problems (see example images).

Design
<img width="562" alt="Screenshot 2021-06-17 at 08 51 58" src="https://user-images.githubusercontent.com/6360479/122355205-a1db5400-cf49-11eb-9334-79d6b4f713aa.png">

Dev (using classes currently available)
<img width="583" alt="Screenshot 2021-06-17 at 09 00 57" src="https://user-images.githubusercontent.com/6360479/122356276-8a509b00-cf4a-11eb-8718-fbcaf8dc9e64.png">

**Comment by catiarodriguescosta** [comment]
Hey, I've came across with this issue before for example here:
https://designsystem.tfwm.org.uk/patterns/buy-a-ticket/
https://designsystem.tfwm.org.uk/patterns/journey-planner/

I created the wmnds-btn--align-left class for these cases:
```
.wmnds-btn--align-left {
    text-align: left;
}
```

```
<button class="wmnds-btn wmnds-col-1 wmnds-col-sm-1-2 wmnds-btn--align-left" type="submit">
    Find tickets
    <svg class="wmnds-btn__icon wmnds-btn__icon--right ">
      <use xlink:href="#wmnds-general-chevron-right" href="#wmnds-general-chevron-right"></use>
    </svg>
  </button>
```

**Comment by daylesalmon** [comment]
As a solution (which shouldn't break existing buttons):
Restyle the main wmnds-btn class so it is left aligned by default and fixes the weird icon issue above.

Then add a new modifier class called wmnds-btn--fullwidth which will make the button...full width.
I would then also make sure the .wmnds-btn.wmnds-col-1 class has the same styling as the new wmnds-btn--fullwidth class as wmnds-col-1 is currently being used to make buttons fullwidth.

When we have finally converted all our services to use the new fullwidth class, we can then remove the wmnds-col-1 class styling from a future version of the design system.

Let me know what you think?

**Comment by houbly** [comment]
I've just given `.wmnds-btn--align-left` a try but it doesn't fully solve the icon/expanding height issue:
<img width="585" alt="Screenshot 2021-06-17 at 10 04 15" src="https://user-images.githubusercontent.com/6360479/122366346-62b20080-cf53-11eb-89ce-49bf9e78a6ba.png">

so I think I'll amend the current `wmnds-btn` with something similar to what Dayle suggested, especially as this also needs to cover use with `a` tags. It will need also to at least support left/center aligned full width buttons and inline buttons. I've already done the icon alignment in the projects but I thought it would be best to have a consistent method for the design system.

**Comment by daylesalmon** [comment]
> I've just given `.wmnds-btn--align-left` a try but it doesn't fully solve the icon/expanding height issue:
> <img alt="Screenshot 2021-06-17 at 10 04 15" width="585" src="https://user-images.githubusercontent.com/6360479/122366346-62b20080-cf53-11eb-89ce-49bf9e78a6ba.png">
> 
> so I think I'll amend the current `wmnds-btn` with something similar to what Dayle suggested, especially as this also needs to cover use with `a` tags. It will need also to at least support left/center aligned full width buttons and inline buttons. I've already done the icon alignment in the projects but I thought it would be best to have a consistent method for the design system.

In hindsight we could of prevented this issue with a modifier class of .wmnds-btn--with-icon or something. 
But it's a bit too late for that now :/
