### ISSUE TITLE
Add map base to styles page

### ISSUE THREAD

**Issue by daylesalmon** [wmcadigital/wmn-design-system#98]
Add the correct mapping style that should be used across WMN services.
This should be the BCCI mapping or as close to as possible.

Provide screenshots of what it should look like.

Relates to: https://github.com/wmcadigital/wmn-sprints/issues/21

**Comment by catiarodriguescosta** [comment]
@daylesalmon Can you provide more info here? :)

**Comment by daylesalmon** [comment]
@catiarodriguescosta I can take this one. As I think some documentation will need to be written up too.
